{{- if and .Values.configOverrides (and .Values.configOverrides.enabled .Values.configOverrides.files) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: firebird-configs-{{ .Values.siteId }}
  labels:
    app: firebird-site
    site: {{ .Values.siteId }}
data:
  {{- range $filename, $content := .Values.configOverrides.files }}
  {{ $filename }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
