{{- if and .Values.ingress.enabled .Values.certificate.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.certificate.name | default (printf "firebird-ssl-cert-%s" .Values.siteId) }}
  labels:
    app: firebird-site
    site: {{ .Values.siteId }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}
