{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: firebird-pdb-{{ .Values.siteId }}
  labels:
    app: firebird-site
    site: {{ .Values.siteId }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: firebird-site
      site: {{ .Values.siteId }}
{{- end }}
