#!/bin/sh
set -e

# ==============================================================================
# 🔥 火鸟门户 Web/PHP 生产容器启动钩子 (云原生动态环境配置注入)
# ==============================================================================

DBINFO_FILE="/var/www/html/include/dbinfo.inc.php"

# 如果配置了外部数据库环境变量，则自动注入
if [ -n "$DB_HOST" ]; then
    cat <<EOF > "$DBINFO_FILE"
<?php
// 火鸟云原生数据库连接配置 (Auto-generated by entrypoint)
\$DB_HOST = '${DB_HOST:-10.0.0.10}';
\$DB_NAME = '${DB_NAME:-firebird_manila}';
\$DB_USER = '${DB_USER:-firebird_user}';
\$DB_PASS = '${DB_PASS:-firebirdpassword}';
\$DB_PREFIX = '${DB_PREFIX:-huoniao_}';
\$DB_CHARSET = 'utf-8';
EOF
    chown www-data:www-data "$DBINFO_FILE" 2>/dev/null || true
fi

# 如果配置了基础域名环境变量，动态更新 siteConfig.inc.php
SITECONFIG_FILE="/var/www/html/include/config/siteConfig.inc.php"
if [ -n "$SITE_BASEHOST" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s/\\\$cfg_basehost = .*/\\\$cfg_basehost = '${SITE_BASEHOST}';/" "$SITECONFIG_FILE"
fi

# 如果配置了远程附件/邮件密钥环境变量，动态注入 siteConfig.inc.php
if [ -n "$GCS_KEY_ID" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s|\\\$cfg_OBSKeyID = .*|\\\$cfg_OBSKeyID = '${GCS_KEY_ID}';|" "$SITECONFIG_FILE"
    sed -i "s|\\\$cfg_OBSKeySecret = .*|\\\$cfg_OBSKeySecret = '${GCS_KEY_SECRET}';|" "$SITECONFIG_FILE"
fi
if [ -n "$RESEND_KEY" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s|\\\$cfg_mailPass = .*|\\\$cfg_mailPass = '${RESEND_KEY}';|" "$SITECONFIG_FILE"
fi

# 如果挂载了声明式 ConfigMap 配置注入目录 (/etc/firebird-configs)，启动时自动同步至 include/config 并赋予写权限
if [ -d "/etc/firebird-configs" ] && [ -n "$(ls -A /etc/firebird-configs 2>/dev/null)" ]; then
    echo ">>> [ConfigMap Engine] 正在从 ConfigMap 注入声明式业务配置..."
    cp -f /etc/firebird-configs/* /var/www/html/include/config/ 2>/dev/null || true
    chown -R www-data:www-data /var/www/html/include/config 2>/dev/null || true
    chmod -R 777 /var/www/html/include/config 2>/dev/null || true
fi

# 确保底层扩展在 webroot 与系统目录下双重就绪 (自愈机制)
if [ ! -f /var/www/html/huoniao.so ] && [ -f /usr/local/lib/php/extensions/no-debug-non-zts-20190902/huoniao.so ]; then
    cp -f /usr/local/lib/php/extensions/no-debug-non-zts-20190902/huoniao.so /var/www/html/huoniao.so 2>/dev/null || true
    chown www-data:www-data /var/www/html/huoniao.so 2>/dev/null || true
fi

# AD-17: 配置了 REDIS_HOST 且镜像带 redis 扩展时，PHP 会话存入 Redis（Pod 重启/多副本不丢登录态）
if [ -n "$REDIS_HOST" ] && php -m 2>/dev/null | grep -qi '^redis$'; then
    {
        echo 'session.save_handler = redis'
        echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_PORT:-6379}\""
    } > /usr/local/etc/php/conf.d/zz-session-redis.ini
fi

# 确保目录与缓存写权限
mkdir -p /var/www/html/data/cache /var/www/html/data/templates_c 2>/dev/null || true
chown -R www-data:www-data /var/www/html/data 2>/dev/null || true

# 启动 PHP-FPM
exec "$@"
