#!/bin/sh
set -e

# ==============================================================================
# 🔥 火鸟门户 Web/PHP 生产容器启动钩子 (云原生动态环境配置注入)
# ==============================================================================

DBINFO_FILE="/var/www/html/include/dbinfo.inc.php"

# 如果配置了外部数据库环境变量，则自动注入
if [ -n "$DB_HOST" ]; then
    cat <<EOF > "$DBINFO_FILE"
<?php
// 火鸟云原生数据库连接配置 (Auto-generated by entrypoint)
\$DB_HOST = '${DB_HOST:-10.0.0.10}';
\$DB_NAME = '${DB_NAME:-firebird_manila}';
\$DB_USER = '${DB_USER:-firebird_user}';
\$DB_PASS = '${DB_PASS:-firebirdpassword}';
\$DB_PREFIX = '${DB_PREFIX:-huoniao_}';
\$DB_CHARSET = 'utf-8';
EOF
    chown www-data:www-data "$DBINFO_FILE" 2>/dev/null || true
fi

# 如果配置了基础域名环境变量，动态更新 siteConfig.inc.php
SITECONFIG_FILE="/var/www/html/include/config/siteConfig.inc.php"
if [ -n "$SITE_BASEHOST" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s/\\\$cfg_basehost = .*/\\\$cfg_basehost = '${SITE_BASEHOST}';/" "$SITECONFIG_FILE"
fi

# 如果配置了远程附件/邮件密钥环境变量，动态注入 siteConfig.inc.php
if [ -n "$GCS_KEY_ID" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s|\\\$cfg_OBSKeyID = .*|\\\$cfg_OBSKeyID = '${GCS_KEY_ID}';|" "$SITECONFIG_FILE"
    sed -i "s|\\\$cfg_OBSKeySecret = .*|\\\$cfg_OBSKeySecret = '${GCS_KEY_SECRET}';|" "$SITECONFIG_FILE"
fi
if [ -n "$RESEND_KEY" ] && [ -f "$SITECONFIG_FILE" ]; then
    sed -i "s|\\\$cfg_mailPass = .*|\\\$cfg_mailPass = '${RESEND_KEY}';|" "$SITECONFIG_FILE"
fi

# 如果挂载了声明式 ConfigMap 配置注入目录 (/etc/firebird-configs)，启动时自动同步至 include/config 并赋予写权限
if [ -d "/etc/firebird-configs" ] && [ -n "$(ls -A /etc/firebird-configs 2>/dev/null)" ]; then
    echo ">>> [ConfigMap Engine] 正在从 ConfigMap 注入声明式业务配置..."
    cp -f /etc/firebird-configs/* /var/www/html/include/config/ 2>/dev/null || true
    chown -R www-data:www-data /var/www/html/include/config 2>/dev/null || true
    chmod -R 777 /var/www/html/include/config 2>/dev/null || true
fi

# 兜底:仓库以 .example 提供但被 gitignore 的业务配置(如 waimai.inc.php),缺失时从 example 生成,
# 否则对应模块 require 直接 Fatal 导致全站 500(2026-10-10 实际故障)
for example in /var/www/html/include/config/*.inc.php.example; do
    [ -f "$example" ] || continue
    real="${example%.example}"
    if [ ! -f "$real" ]; then
        echo ">>> [Config Fallback] ${real##*/} 缺失,从 example 生成默认配置"
        cp -f "$example" "$real" && chown www-data:www-data "$real" 2>/dev/null || true
    fi
done

# 确保底层扩展在 webroot 与系统目录下双重就绪 (自愈机制)
if [ ! -f /var/www/html/huoniao.so ] && [ -f /usr/local/lib/php/extensions/no-debug-non-zts-20190902/huoniao.so ]; then
    cp -f /usr/local/lib/php/extensions/no-debug-non-zts-20190902/huoniao.so /var/www/html/huoniao.so 2>/dev/null || true
    chown www-data:www-data /var/www/html/huoniao.so 2>/dev/null || true
fi

# AD-17: 配置了 REDIS_HOST 且镜像带 redis 扩展、Redis 可连通时，PHP 会话存入 Redis（Pod 重启/多副本不丢登录态）
# Redis 不可达则回退文件会话并告警，避免 session_start() 全站失败
if [ -n "$REDIS_HOST" ] && php -m 2>/dev/null | grep -qi '^redis$'; then
    if php -r '$r=new Redis(); exit($r->connect(getenv("REDIS_HOST"),(int)(getenv("REDIS_PORT")?:6379),2)?0:1);' 2>/dev/null; then
        {
            echo 'session.save_handler = redis'
            echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_PORT:-6379}?timeout=2&prefix=PHPREDIS_SESSION_${SITE_ID:-site}:${REDIS_PASSWORD:+&auth=${REDIS_PASSWORD}}\""
        } > /usr/local/etc/php/conf.d/zz-session-redis.ini
    else
        echo ">>> [WARN] Redis ${REDIS_HOST}:${REDIS_PORT:-6379} 不可达，会话回退为文件存储" >&2
    fi
fi

# 确保目录与缓存写权限
mkdir -p /var/www/html/data/cache /var/www/html/data/templates_c 2>/dev/null || true
chown -R www-data:www-data /var/www/html/data 2>/dev/null || true

# 启动 PHP-FPM
exec "$@"
